### ISSUE TITLE
USER STORY: new member getting advice through feedback

### ISSUE THREAD

**Issue by AnnieNeilson** [AnnieNeilson/My-First-Agile-Project#4]
As a **new club member** I can **see other members' feedback on tracks** so that **I can choose the best tracks for my running level**

## Acceptance Criteria:

1. When giving feedback there should be a dropdown option for users to specify the track they are referring to
2. When giving feedback there should be an option for the user to upload photos
3. The feedback should be able to be commented on and up or down voted

## Tasks:

- [ ] Create the HTML and CSS for the dropdown menu including the names of the running tracks
- [ ] Create the HTML and CSS for the upload button, allowing for images up to 250KB
- [ ] Create the HTML and CSS for the upvote and down vote buttons and a count for each one
- [ ] Create the HTML and CSS for a comment section on each post
- [ ] Test functionality
