### ISSUE TITLE
USER STORY: Respond to polls anonymously

### ISSUE THREAD

**Issue by AnnieNeilson** [AnnieNeilson/My-First-Agile-Project#5]
As a **club member** I can **provide anonymous feedback** so that **I can choose to hide my identity in a poll**

## Acceptance Criteria:

1. The option to be show user name should appear next to the submit button
2. The option should be a checkbox
3. The option should be automatically checked
4. After deselecting this option, and submitting the poll response the response should appear without a user name

## Tasks:

- [ ] Update the HTML and CSS of the poll design to include a checked checkbox and show the username
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Test the functionality
