### ISSUE TITLE
USER STORY: Admin control over user posts

### ISSUE THREAD

**Issue by AnnieNeilson** [AnnieNeilson/My-First-Agile-Project#6]
As a **site administrator** I can **review and hide user feedback** so that **I can assure posts to the site are appropriate and hide anything that is not**

## Acceptance Criteria:

1. The site admin are notified when a post is uploaded to the site
2. Only the admin can see the post until it is approved
3. Once approved the post is uploaded to the site and the original poster is notified that is had been approved

## Tasks:

- [ ] Develop an alert that notifies the admin of a new post
- [ ] Create a message that appears to the original poster to let them know their post is being reviewed
- [ ] Create the code for the model, viewer ad controller
- [ ] Test functionality
